sudo: required
dist: trusty

language: cpp

services: docker

cache:
  directories:
    - $HOME/travisCacheDir

matrix:
  fast_finish: true

matrix:
  include:
    - os: linux
      env: BUILD_TYPE=Debug
    - os: linux
      env: BUILD_TYPE=Release

before_install:
  - docker pull berkus/docker-cpp-ci:latest

script:
  - mkdir _build_
  - docker run --rm -v $PWD:/repo -v ~/.travis:/travis berkus/docker-cpp-ci /bin/sh -c "/repo/.travis/build.sh"
